import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AdminLanguage = "en" | "ar";

const STORAGE_KEY = "warqless_admin_language";

const translations = {
  en: {
    app: {
      name: "Warqless",
      panel: "Admin Panel",
      publisherPanel: "Publisher Panel",
    },
    common: {
      all: "all",
      active: "active",
      suspended: "suspended",
      published: "published",
      draft: "draft",
      completed: "completed",
      refunded: "refunded",
      pending: "pending",
      approved: "approved",
      rejected: "rejected",
      returned: "returned",
      overdue: "overdue",
      total: "total",
      books: "Books",
      revenue: "Revenue",
      orders: "Orders",
      status: "Status",
      date: "Date",
      amount: "Amount",
      price: "Price",
      sales: "Sales",
      student: "Student",
      publisher: "Publisher",
      subject: "Subject",
      book: "Book",
      edit: "Edit",
      view: "View",
      suspend: "Suspend",
      reactivate: "Reactivate",
      restore: "Restore",
      recall: "Recall",
      exportCsv: "Export CSV",
      saveChanges: "Save Changes",
      saved: "Saved!",
      signOut: "Sign out",
      search: "Search",
      noResults: "No results match your filters.",
      vsLastMonth: "vs last month",
      noChangeVsLastMonth: "No change vs last month",
      last6Months: "Last 6 months",
      units: "Units",
      joined: "Joined",
      role: "Role",
      name: "Name",
      email: "Email",
      newPassword: "New Password",
      leaveBlank: "Leave blank to keep current",
    },
    roles: {
      admin: "Admin",
      publisher: "Publisher",
    },
    education: {
      field: "Educational stage",
      groups: {
        primary: "Primary stage",
        preparatory: "Preparatory stage",
        secondary: "General secondary stage",
        technical_secondary: "Technical secondary education",
      },
      levels: {
        primary_1: "Grade 1 / Year 1",
        primary_2: "Grade 2 / Year 2",
        primary_3: "Grade 3 / Year 3",
        primary_4: "Grade 4 / Year 4",
        primary_5: "Grade 5 / Year 5",
        primary_6: "Grade 6 / Year 6",
        preparatory_1: "Grade 7 / Year 7",
        preparatory_2: "Grade 8 / Year 8",
        preparatory_3: "Grade 9 / Year 9",
        secondary_1: "Grade 10 / Year 10 / IGCSE",
        secondary_2: "Grade 11 / Year 11 / IGCSE",
        secondary_3: "Grade 12 / Year 12 / AS/A Level",
        technical_secondary_1: "Technical secondary year 1",
        technical_secondary_2: "Technical secondary year 2",
        technical_secondary_3: "Technical secondary year 3",
      },
    },
    nav: {
      dashboard: "Dashboard",
      books: "Books",
      publishers: "Publishers",
      students: "Students",
      orders: "Orders",
      lending: "Lending",
      security: "Security",
      settings: "Settings",
    },
    login: {
      title: "Sign in",
      subtitle: "For publishers and administrators only.",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      invalid: "Invalid credentials. Please try again.",
      demoCredentials: "Demo credentials",
      brandSubtitle: "Publisher & Admin Dashboard",
      statsBooks: "Books",
      statsStudents: "Students",
      statsRevenue: "Revenue",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: (name: string) => `Welcome back, ${name}. Here is your overview.`,
      totalRevenue: "Total Revenue",
      totalRevenueDesc: (isAdmin: boolean): string =>
        isAdmin ? "From all publisher book sales" : "From your book sales",
      publishedBooks: "Published Books",
      draftsPending: (count: number) => `${count} drafts pending`,
      activeStudents: "Active Students",
      suspendedStudents: (count: number) => `${count} suspended`,
      publishers: "Publishers",
      registeredPublishers: (count: number) => `${count} total registered`,
      allTime: "All time",
      activeLending: "Active Lending",
      overdueSummary: (count: number) => `${count} overdue`,
      overdueAlert: (count: number) => `${count} lending record${count > 1 ? "s" : ""} overdue — review in the Lending section.`,
      revenueChart: "Revenue",
      subjectBreakdown: "Sales by Subject",
      unitsSold: "Units sold",
      recentOrders: "Recent Orders",
      monthOverMonth: "MoM",
    },
    books: {
      title: "Books",
      subtitle: (published: number, sales: string, revenue: string) =>
        `${published} published · ${sales} total sales · ${revenue} revenue`,
      addBook: "Add Book",
      bookDetails: "Book details",
      bookDetailsDesc: "Add the core details for a new publisher book.",
      publisherField: "Publisher",
      selectPublisher: "Select publisher",
      bookNameField: "Book name",
      bookNamePlaceholder: "Enter book title",
      subjectField: "Subject",
      selectSubject: "Select subject",
      publisherSubjectsHint: (publisher: string): string => `Subjects already used by ${publisher}`,
      classificationField: "Classification",
      selectClassification: "Select classification",
      classificationRequired: "Please select a classification.",
      noMatchingPublisherContent:
        "No matching publisher content found. You can still choose a classification for this MVP.",
      classificationNames: {
        term1: "First term",
        term2: "Second term",
        full_year: "Full year",
        final_revision: "Final revision",
        question_bank: "Question bank",
        workbook: "Workbook",
        exam_preparation: "Exam preparation",
        answer_book: "Answer book",
        other: "Other",
      },
      publicationStatus: "Publication status",
      publishBook: "Publish book",
      priceField: "Price",
      commissionField: "Warqless commission (%)",
      optionalOptions: "Optional options",
      couponCode: "Discount coupon",
      couponPlaceholder: "Example: BACK2SCHOOL",
      discountField: "Discount (%)",
      discountResponsibility: "Discount paid by",
      discountPaidByPlatform: "Warqless",
      discountPaidByPublisher: "Publisher",
      discountShared: "Split equally",
      finalPrice: "Final price",
      listPrice: "List price",
      customerPrice: "Customer price",
      discountValue: "Discount value",
      commercialSummary: "Commercial summary",
      commissionValue: "Warqless commission",
      platformDiscountCost: "Warqless discount cost",
      publisherDiscountCost: "Publisher discount cost",
      adminNetPerCopy: "Warqless net per copy",
      adminNetMargin: "Warqless net margin",
      publisherNetPerCopy: "Publisher net per copy",
      publisherNetMargin: "Publisher net margin",
      saveDraft: "Save as draft",
      deleteBook: "Delete Book",
      deleteBookTitle: "Delete book?",
      deleteBookMessage:
        "Are you sure you want to delete this book? This action will remove it from the books list.",
      bookDeletedSuccess: "Book deleted successfully.",
      cancel: "Cancel",
      searchPlaceholder: "Search by title, subject, publisher...",
      noBooks: "No books match your filters.",
      gradeAndType: (grade: string, type: string) => `${grade} · ${type}`,
      gradeClassificationAndType: (grade: string, classification: string, type: string) =>
        `${grade} · ${classification} · ${type}`,
    },
    publishers: {
      title: "Publishers",
      subtitle: (active: number, books: number, revenue: string) =>
        `${active} active · ${books} books · ${revenue} total revenue`,
      addPublisher: "Add Publisher",
      publisherDetails: "Publisher details",
      publisherDetailsDesc: "Create a publisher account and define the content they can manage.",
      accountSection: "Publisher account",
      accountSectionDesc: "These credentials are used to sign in as a publisher.",
      publisherDataSection: "Publisher data",
      contentSection: "Publisher content",
      accountName: "Account name",
      accountNamePlaceholder: "Example: Ahmed Mansour",
      tradeName: "Commercial name",
      tradeNamePlaceholder: "Name shown to students",
      password: "Password",
      passwordPlaceholder: "Minimum 6 characters",
      bookLanguages: "Book language",
      academicYears: "Academic year",
      subjects: "Subject",
      subjectsPlaceholder: "Mathematics",
      classification: "Classification",
      languageNames: {
        ar: "Arabic",
        en: "English",
        fr: "French",
        de: "German",
      },
      classificationNames: {
        term1: "First term",
        term2: "Second term",
        questions_practice: "Question and practice book",
        explanation: "Explanation book",
        revision: "Revision book",
        notes: "Notes",
        booklet: "Booklet",
        workbook: "Workbook",
      },
      commaHint: "Add one subject per row. Use + to add more.",
      addContent: "Add content",
      removeContent: "Remove content",
      deleteContent: "Delete",
      deleteContentTitle: "Delete content row?",
      deleteContentMessage: "Are you sure you want to delete this publisher content/version row?",
      deleteContentConfirm: "Delete",
      noContentAdded: "No publisher content added yet.",
      contentItem: (index: number) => `Content ${index}`,
      loginReady: "Publisher can sign in after saving with the email and password above.",
      emailAlreadyExists: "This email is already used by another publisher.",
      savePublisher: "Create publisher",
      deletePublisher: "Delete Publisher",
      deletePublisherTitle: "Delete publisher?",
      deletePublisherMessage:
        "Are you sure you want to delete this publisher? This action will remove the publisher from the admin list and may affect their books/content.",
      deletePublisherBooksWarning:
        "This publisher has books/content. Deleting it may remove or orphan related content.",
      publisherDeletedSuccess: "Publisher deleted successfully.",
      searchPlaceholder: "Search publishers...",
      noPublishers: "No publishers match your search.",
      viewBooks: "View Books",
    },
    students: {
      title: "Students",
      subtitle: (active: number, spent: string) => `${active} active students · ${spent} total spent`,
      searchPlaceholder: "Search students...",
      noStudents: "No students match your filters.",
      grade: "Grade",
      borrowed: "Borrowed",
      devices: "Devices",
      spent: "Spent",
      detailsTitle: "Student details",
      detailsDescription: "Full account, usage, orders, and lending data stored for this student.",
      publisherDetailsDescription: "Full account, usage, and orders data stored for this student.",
      accountDetails: "Account details",
      learningProfile: "Learning profile",
      activitySummary: "Activity summary",
      studentId: "Student ID",
      phone: "Phone",
      joinedAt: "Joined at",
      booksOwned: "Owned books",
      borrowedBooks: "Borrowed books",
      linkedDevices: "Linked devices",
      totalSpent: "Total spent",
      ordersHistory: "Orders history",
      lendingHistory: "Lending history",
      orderId: "Order ID",
      bookId: "Book ID",
      publisherId: "Publisher ID",
      lendingId: "Lending ID",
      ownerId: "Owner ID",
      borrowerId: "Borrower ID",
      owner: "Owner",
      borrower: "Borrower",
      lentAt: "Lent",
      dueAt: "Due",
      returnedAt: "Returned",
      notReturnedYet: "Not returned yet",
      noOrders: "No orders recorded for this student.",
      noLending: "No lending activity recorded for this student.",
      deviceSecurity: "Device & security",
      currentDevice: "Current device",
      deviceId: "Device ID",
      maskedDeviceId: "Masked device ID",
      platform: "Platform",
      osVersion: "OS version",
      appVersion: "App version",
      deviceName: "Device name",
      registeredAt: "Registered at",
      lastVerifiedAt: "Last verified",
      deviceStatus: "Device status",
      deviceHistory: "Device history",
      changeRequests: "Device change requests",
      noDeviceData: "No device data synced yet.",
      noChangeRequests: "No device change requests.",
      securityEvents: "Security events",
      noSecurityEvents: "No security events recorded.",
      couponsTitle: "Coupons",
      usedCoupons: "Used coupons",
      unusedCoupons: "Unused coupons",
      noUsedCoupons: "No used coupons.",
      noUnusedCoupons: "No unused coupons.",
      couponCode: "Coupon code",
      discount: "Discount",
      usedAt: "Used at",
      passwordSecurity: "Password & auth",
      passwordValue: "Password value",
      hiddenByDesign: "Hidden by design",
      passwordSet: "Password set",
      passwordStorage: "Password storage",
      passwordHashStored: "Hash stored",
      passwordLastChanged: "Last password change",
      lastLogin: "Last login",
      failedLoginAttempts: "Failed login attempts",
      authProvider: "Auth provider",
      yes: "Yes",
      no: "No",
      never: "Never",
      suspendTitle: "Suspend student?",
      suspendMessage: (name: string) => `${name} will lose access until you restore the account.`,
      restoreTitle: "Restore student?",
      restoreMessage: (name: string) => `${name} will regain access to the student account.`,
      confirmSuspend: "Suspend student",
      confirmRestore: "Restore student",
      suspendSuccess: (name: string) => `${name} has been suspended.`,
      restoreSuccess: (name: string) => `${name} has been restored.`,
    },
    orders: {
      title: "Orders",
      subtitle: (orders: number, revenue: string, refunded: string) =>
        `${orders} orders · ${revenue} revenue · ${refunded} refunded`,
      searchPlaceholder: "Search by student or book...",
      noOrders: "No orders match your filters.",
      order: "Order",
      exportExcel: "Export Excel",
      refresh: "Refresh",
      lastSynced: (time: string) => `Updated ${time}`,
      loading: "Loading orders...",
      loadError: "Could not load live orders from the local API.",
      coupon: "Coupon",
      discount: "Discount",
      netAmount: "Net amount",
    },
    lending: {
      title: "Lending",
      subtitle: (active: number, returned: number, overdue: number) =>
        `${active} active · ${returned} returned · ${overdue} overdue`,
      activeLoans: "Active Loans",
      owner: "Owner",
      borrower: "Borrower",
      lent: "Lent",
      due: "Due",
      returned: "Returned",
      noRecords: "No lending records match your filter.",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account and platform preferences",
      account: "Account",
      platform: "Platform",
      notifications: "Notifications",
      security: "Security",
      interface: "Interface",
      adminLanguage: "Admin interface language",
      adminLanguageDesc: "Choose the language and text direction used in this dashboard.",
      english: "English",
      arabic: "Arabic",
      enableLending: "Enable Book Lending",
      enableLendingDesc: "Allow students to lend books to other students",
      autoSuspend: "Auto-suspend Overdue Borrowers",
      autoSuspendDesc: "Suspend borrowers who exceed the lending period by 7+ days",
      studentArabic: "Arabic Interface for Students",
      studentArabicDesc: "Set Arabic as the default language in the mobile app",
      emailNotifications: "Email Notifications",
      emailNotificationsDesc: "Receive emails for new orders and important events",
      overdueAlerts: "Overdue Lending Alerts",
      overdueAlertsDesc: "Get notified when a borrowed book is overdue",
      twoFactor: "Two-Factor Authentication",
      twoFactorDesc: "Add an extra layer of security to your admin account",
    },
    security: {
      title: "Security & Monitoring",
      subtitle: "Track security events, device activity, and content protection across the platform.",
      totalEvents: "Total Events",
      deviceBlocked: "Device Blocked",
      accessDenied: "Access Denied",
      screenshots: "Screenshots",
      pendingResets: "Pending Resets",
      criticalEvents: "Critical Events",
      resetRequests: "Device Reset Requests",
      resetRequestsDesc: "Students requesting to link a new physical device to their account",
      securityEvents: "Security Events",
      searchEvents: "Search events...",
      searchRequests: "Search requests...",
      allSeverity: "All Severity",
      allTypes: "All Types",
      allStatuses: "All Statuses",
      dateFrom: "From date",
      dateTo: "To date",
      event: "Event",
      severity: "Severity",
      device: "Device",
      time: "Time",
      reason: "Reason",
      submitted: "Submitted",
      resolved: "Resolved",
      approve: "Approve",
      reject: "Reject",
      approveHint: "Approving allows the student to register a new device on next login.",
      reviewed: "Reviewed",
      markReviewed: "Mark as reviewed",
      loading: "Loading...",
      loadError: "Could not load live security data from the local API.",
      noComparisonData: "No comparison data yet",
      approveSuccess: "Device reset request approved.",
      rejectSuccess: "Device reset request rejected.",
      reviewSuccess: "Security event marked as reviewed.",
      actionError: "Action failed",
      noResetRequests: "No device reset requests.",
      noEvents: "No events match the current filters.",
      mvpTitle: "Live API Mode",
      mvpLine1: "This page now reads security metrics, events, and device reset requests from the local backend API.",
      mvpLine2: "The backend still uses the local demo JSON store until the Drizzle/Postgres migration is applied.",
      detailsStudent: "Student",
      detailsBook: "Book",
      detailsDevice: "Device",
      detailsMessage: "Message",
      detailsMetadata: "Metadata",
      recommendedAction: "Recommended Action",
      recommendedDefault: "Review this event and take appropriate action.",
      eventTypes: {
        device_registered: "Device Registered",
        device_verified: "Device Verified",
        device_blocked: "Device Blocked",
        device_reset_requested: "Reset Requested",
        device_reset_approved: "Reset Approved",
        device_reset_rejected: "Reset Rejected",
        reader_opened: "Reader Opened",
        reader_access_denied: "Access Denied",
        license_check_failed: "License Failed",
        screenshot_attempt: "Screenshot Attempt",
        suspicious_activity: "Suspicious Activity",
        phone_changed: "Phone Changed",
        phone_verification_code_sent: "Phone Code Sent",
        phone_verified: "Phone Verified",
        phone_verification_failed: "Phone Verification Failed",
        two_factor_enabled: "2FA Enabled",
        two_factor_disabled: "2FA Disabled",
        two_factor_challenge_sent: "2FA Challenge Sent",
        two_factor_success: "2FA Success",
        two_factor_failed: "2FA Failed",
      },
      severities: {
        low: "low",
        medium: "medium",
        high: "high",
        critical: "critical",
      },
    },
  },
  ar: {
    app: {
      name: "Warqless",
      panel: "لوحة الإدارة",
      publisherPanel: "لوحة الناشر",
    },
    common: {
      all: "الكل",
      active: "نشط",
      suspended: "موقوف",
      published: "منشور",
      draft: "مسودة",
      completed: "مكتمل",
      refunded: "مسترد",
      pending: "قيد الانتظار",
      approved: "مقبول",
      rejected: "مرفوض",
      returned: "تم الإرجاع",
      overdue: "متأخر",
      total: "الإجمالي",
      books: "الكتب",
      revenue: "الإيراد",
      orders: "الطلبات",
      status: "الحالة",
      date: "التاريخ",
      amount: "المبلغ",
      price: "السعر",
      sales: "المبيعات",
      student: "الطالب",
      publisher: "الناشر",
      subject: "المادة",
      book: "الكتاب",
      edit: "تعديل",
      view: "عرض",
      suspend: "إيقاف",
      reactivate: "تفعيل",
      restore: "استعادة",
      recall: "استرجاع",
      exportCsv: "تصدير CSV",
      saveChanges: "حفظ التغييرات",
      saved: "تم الحفظ",
      signOut: "تسجيل الخروج",
      search: "بحث",
      noResults: "لا توجد نتائج مطابقة للفلاتر.",
      vsLastMonth: "مقارنة بالشهر السابق",
      noChangeVsLastMonth: "بدون تغيير عن الشهر السابق",
      last6Months: "آخر 6 أشهر",
      units: "وحدة",
      joined: "انضم",
      role: "الدور",
      name: "الاسم",
      email: "البريد الإلكتروني",
      newPassword: "كلمة مرور جديدة",
      leaveBlank: "اتركه فارغا للإبقاء على الحالية",
    },
    roles: {
      admin: "مدير",
      publisher: "ناشر",
    },
    education: {
      field: "المرحلة التعليمية",
      groups: {
        primary: "المرحلة الابتدائية",
        preparatory: "المرحلة الإعدادية",
        secondary: "المرحلة الثانوية العامة",
        technical_secondary: "التعليم الفني الثانوي",
      },
      levels: {
        primary_1: "الصف الأول الابتدائي",
        primary_2: "الصف الثاني الابتدائي",
        primary_3: "الصف الثالث الابتدائي",
        primary_4: "الصف الرابع الابتدائي",
        primary_5: "الصف الخامس الابتدائي",
        primary_6: "الصف السادس الابتدائي",
        preparatory_1: "الصف الأول الإعدادي",
        preparatory_2: "الصف الثاني الإعدادي",
        preparatory_3: "الصف الثالث الإعدادي",
        secondary_1: "الصف الأول الثانوي",
        secondary_2: "الصف الثاني الثانوي",
        secondary_3: "الصف الثالث الثانوي",
        technical_secondary_1: "الصف الأول الثانوي الفني",
        technical_secondary_2: "الصف الثاني الثانوي الفني",
        technical_secondary_3: "الصف الثالث الثانوي الفني",
      },
    },
    nav: {
      dashboard: "لوحة التحكم",
      books: "الكتب",
      publishers: "الناشرون",
      students: "الطلاب",
      orders: "الطلبات",
      lending: "الإعارة",
      security: "الأمان",
      settings: "الإعدادات",
    },
    login: {
      title: "تسجيل الدخول",
      subtitle: "للناشرين والمديرين فقط.",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      submit: "دخول",
      invalid: "بيانات الدخول غير صحيحة. حاول مرة أخرى.",
      demoCredentials: "بيانات تجريبية",
      brandSubtitle: "لوحة الناشرين والإدارة",
      statsBooks: "كتب",
      statsStudents: "طلاب",
      statsRevenue: "إيراد",
    },
    dashboard: {
      title: "لوحة التحكم",
      subtitle: (name: string) => `مرحبا ${name}، هذه نظرة عامة على الأداء.`,
      totalRevenue: "إجمالي الإيراد",
      totalRevenueDesc: (isAdmin: boolean): string =>
        isAdmin ? "من مبيعات كتب كل الناشرين" : "من مبيعات كتبك",
      publishedBooks: "الكتب المنشورة",
      draftsPending: (count: number) => `${count} مسودات قيد المراجعة`,
      activeStudents: "الطلاب النشطون",
      suspendedStudents: (count: number) => `${count} موقوف`,
      publishers: "الناشرون",
      registeredPublishers: (count: number) => `${count} مسجلين إجمالا`,
      allTime: "كل الوقت",
      activeLending: "الإعارات النشطة",
      overdueSummary: (count: number) => `${count} متأخر`,
      overdueAlert: (count: number) => `${count} سجل إعارة متأخر — راجعه من قسم الإعارة.`,
      revenueChart: "الإيراد",
      subjectBreakdown: "المبيعات حسب المادة",
      unitsSold: "الوحدات المباعة",
      recentOrders: "أحدث الطلبات",
      monthOverMonth: "شهريا",
    },
    books: {
      title: "الكتب",
      subtitle: (published: number, sales: string, revenue: string) =>
        `${published} منشور · ${sales} مبيعات إجمالية · ${revenue} إيراد`,
      addBook: "إضافة كتاب",
      bookDetails: "تفاصيل الكتاب",
      bookDetailsDesc: "أدخل البيانات الأساسية لكتاب جديد تابع لناشر.",
      publisherField: "الناشر",
      selectPublisher: "اختر الناشر",
      bookNameField: "اسم الكتاب",
      bookNamePlaceholder: "اكتب اسم الكتاب",
      subjectField: "اسم المادة",
      selectSubject: "اختر المادة",
      publisherSubjectsHint: (publisher: string): string => `المواد الموجودة بالفعل لدى ${publisher}`,
      classificationField: "التصنيف",
      selectClassification: "اختر التصنيف",
      classificationRequired: "برجاء اختيار التصنيف.",
      noMatchingPublisherContent:
        "لا يوجد محتوى ناشر مطابق. يمكنك اختيار تصنيف لهذا الإصدار التجريبي.",
      classificationNames: {
        term1: "الترم الأول",
        term2: "الترم الثاني",
        full_year: "العام كامل",
        final_revision: "مراجعة نهائية",
        question_bank: "بنك أسئلة",
        workbook: "كراسة تدريبات",
        exam_preparation: "تحضير امتحانات",
        answer_book: "كتاب إجابات",
        other: "أخرى",
      },
      publicationStatus: "حالة النشر",
      publishBook: "نشر الكتاب",
      priceField: "السعر",
      commissionField: "عمولة Warqless (%)",
      optionalOptions: "خيارات اختيارية",
      couponCode: "كوبون خصم",
      couponPlaceholder: "مثال: BACK2SCHOOL",
      discountField: "خصم (%)",
      discountResponsibility: "الخصم يتحمله",
      discountPaidByPlatform: "Warqless",
      discountPaidByPublisher: "الناشر",
      discountShared: "مناصفة",
      finalPrice: "السعر النهائي",
      listPrice: "سعر القائمة",
      customerPrice: "سعر الطالب",
      discountValue: "قيمة الخصم",
      commercialSummary: "ملخص تجاري ومحاسبي",
      commissionValue: "عمولة Warqless",
      platformDiscountCost: "تكلفة الخصم على Warqless",
      publisherDiscountCost: "تكلفة الخصم على الناشر",
      adminNetPerCopy: "صافي Warqless لكل نسخة",
      adminNetMargin: "نسبة صافي Warqless",
      publisherNetPerCopy: "صافي الناشر لكل نسخة",
      publisherNetMargin: "نسبة صافي الناشر",
      saveDraft: "حفظ كمسودة",
      deleteBook: "حذف الكتاب",
      deleteBookTitle: "هل تريد حذف هذا الكتاب؟",
      deleteBookMessage: "سيتم حذف هذا الكتاب من قائمة الكتب.",
      bookDeletedSuccess: "تم حذف الكتاب بنجاح.",
      cancel: "إلغاء",
      searchPlaceholder: "ابحث بالعنوان أو المادة أو الناشر...",
      noBooks: "لا توجد كتب مطابقة للفلاتر.",
      gradeAndType: (grade: string, type: string) => `${grade} · ${type}`,
      gradeClassificationAndType: (grade: string, classification: string, type: string) =>
        `${grade} · ${classification} · ${type}`,
    },
    publishers: {
      title: "الناشرون",
      subtitle: (active: number, books: number, revenue: string) =>
        `${active} نشط · ${books} كتاب · ${revenue} إجمالي الإيراد`,
      addPublisher: "إضافة ناشر",
      publisherDetails: "تفاصيل الناشر",
      publisherDetailsDesc: "أنشئ حساب ناشر وحدد المحتوى الذي يمكنه إدارته.",
      accountSection: "حساب الناشر",
      accountSectionDesc: "بيانات الدخول التي يستخدمها الناشر لتسجيل الدخول.",
      publisherDataSection: "بيانات الناشر",
      contentSection: "محتوى الناشر",
      accountName: "اسم الحساب",
      accountNamePlaceholder: "مثال: أحمد منصور",
      tradeName: "الاسم التجاري",
      tradeNamePlaceholder: "الاسم الظاهر للطلاب",
      password: "كلمة المرور",
      passwordPlaceholder: "6 أحرف على الأقل",
      bookLanguages: "لغة الكتاب",
      academicYears: "السنة الدراسية",
      subjects: "المادة",
      subjectsPlaceholder: "رياضيات",
      classification: "التصنيف",
      languageNames: {
        ar: "عربي",
        en: "إنجليزي",
        fr: "فرنسي",
        de: "ألماني",
      },
      classificationNames: {
        term1: "ترم أول",
        term2: "ترم ثاني",
        questions_practice: "كتاب أسئلة وتدريبات",
        explanation: "كتاب شرح",
        revision: "كتاب مراجعة",
        notes: "مذكرة",
        booklet: "كتيب",
        workbook: "كراسة",
      },
      commaHint: "أضف مادة واحدة في كل صف. استخدم + لإضافة مواد أخرى.",
      addContent: "إضافة محتوى",
      removeContent: "حذف المحتوى",
      deleteContent: "حذف",
      deleteContentTitle: "هل تريد حذف هذا الإصدار؟",
      deleteContentMessage: "سيتم حذف هذا الإصدار/التصنيف من بيانات الناشر.",
      deleteContentConfirm: "حذف",
      noContentAdded: "لم تتم إضافة محتوى للناشر بعد.",
      contentItem: (index: number) => `محتوى ${index}`,
      loginReady: "يمكن للناشر تسجيل الدخول بعد الحفظ باستخدام الإيميل وكلمة المرور أعلاه.",
      emailAlreadyExists: "هذا البريد مستخدم بالفعل لناشر آخر.",
      savePublisher: "إنشاء الناشر",
      deletePublisher: "حذف الناشر",
      deletePublisherTitle: "هل تريد حذف هذا الناشر؟",
      deletePublisherMessage: "سيتم حذف الناشر من قائمة الناشرين وقد يؤثر ذلك على الكتب والمحتوى المرتبط به.",
      deletePublisherBooksWarning: "هذا الناشر لديه كتب/محتوى. قد يؤدي الحذف إلى إزالة المحتوى المرتبط أو تركه بدون ناشر.",
      publisherDeletedSuccess: "تم حذف الناشر بنجاح.",
      searchPlaceholder: "ابحث في الناشرين...",
      noPublishers: "لا يوجد ناشرون مطابقون للبحث.",
      viewBooks: "عرض الكتب",
    },
    students: {
      title: "الطلاب",
      subtitle: (active: number, spent: string) => `${active} طالب نشط · ${spent} إجمالي الإنفاق`,
      searchPlaceholder: "ابحث في الطلاب...",
      noStudents: "لا يوجد طلاب مطابقون للفلاتر.",
      grade: "الصف",
      borrowed: "المستعار",
      devices: "الأجهزة",
      spent: "الإنفاق",
      detailsTitle: "تفاصيل الطالب",
      detailsDescription: "كل بيانات الحساب والاستخدام والطلبات والإعارة المسجلة لهذا الطالب.",
      publisherDetailsDescription: "كل بيانات الحساب والاستخدام والطلبات المسجلة لهذا الطالب.",
      accountDetails: "بيانات الحساب",
      learningProfile: "البيانات التعليمية",
      activitySummary: "ملخص النشاط",
      studentId: "معرف الطالب",
      phone: "رقم الهاتف",
      joinedAt: "تاريخ الانضمام",
      booksOwned: "الكتب المملوكة",
      borrowedBooks: "الكتب المستعارة",
      linkedDevices: "الأجهزة المرتبطة",
      totalSpent: "إجمالي الإنفاق",
      ordersHistory: "سجل الطلبات",
      lendingHistory: "سجل الإعارة",
      orderId: "معرف الطلب",
      bookId: "معرف الكتاب",
      publisherId: "معرف الناشر",
      lendingId: "معرف الإعارة",
      ownerId: "معرف المالك",
      borrowerId: "معرف المستعير",
      owner: "مالك",
      borrower: "مستعير",
      lentAt: "تاريخ الإعارة",
      dueAt: "تاريخ الاستحقاق",
      returnedAt: "تاريخ الإرجاع",
      notReturnedYet: "لم يتم الإرجاع بعد",
      noOrders: "لا توجد طلبات مسجلة لهذا الطالب.",
      noLending: "لا يوجد نشاط إعارة مسجل لهذا الطالب.",
      deviceSecurity: "الجهاز والأمان",
      currentDevice: "الجهاز الحالي",
      deviceId: "معرف الجهاز",
      maskedDeviceId: "معرف الجهاز المخفي",
      platform: "النظام",
      osVersion: "إصدار النظام",
      appVersion: "إصدار التطبيق",
      deviceName: "اسم الجهاز",
      registeredAt: "تاريخ التسجيل",
      lastVerifiedAt: "آخر تحقق",
      deviceStatus: "حالة الجهاز",
      deviceHistory: "سجل الأجهزة",
      changeRequests: "طلبات تغيير الجهاز",
      noDeviceData: "لم تتم مزامنة بيانات الجهاز بعد.",
      noChangeRequests: "لا توجد طلبات تغيير جهاز.",
      securityEvents: "أحداث الأمان",
      noSecurityEvents: "لا توجد أحداث أمان مسجلة.",
      couponsTitle: "الكوبونات",
      usedCoupons: "الكوبونات المستخدمة",
      unusedCoupons: "الكوبونات غير المستخدمة",
      noUsedCoupons: "لا توجد كوبونات مستخدمة.",
      noUnusedCoupons: "لا توجد كوبونات غير مستخدمة.",
      couponCode: "كود الكوبون",
      discount: "الخصم",
      usedAt: "تاريخ الاستخدام",
      passwordSecurity: "كلمة المرور وتسجيل الدخول",
      passwordValue: "قيمة كلمة المرور",
      hiddenByDesign: "مخفية لأسباب أمنية",
      passwordSet: "كلمة المرور موجودة",
      passwordStorage: "تخزين كلمة المرور",
      passwordHashStored: "الهاش محفوظ",
      passwordLastChanged: "آخر تغيير لكلمة المرور",
      lastLogin: "آخر تسجيل دخول",
      failedLoginAttempts: "محاولات الدخول الفاشلة",
      authProvider: "طريقة الدخول",
      yes: "نعم",
      no: "لا",
      never: "لم يحدث",
      suspendTitle: "إيقاف الطالب؟",
      suspendMessage: (name: string) => `سيتم منع ${name} من الوصول للحساب حتى تتم استعادته.`,
      restoreTitle: "استعادة الطالب؟",
      restoreMessage: (name: string) => `سيتم السماح لـ ${name} بالوصول لحساب الطالب مرة أخرى.`,
      confirmSuspend: "إيقاف الطالب",
      confirmRestore: "استعادة الطالب",
      suspendSuccess: (name: string) => `تم إيقاف ${name}.`,
      restoreSuccess: (name: string) => `تمت استعادة ${name}.`,
    },
    orders: {
      title: "الطلبات",
      subtitle: (orders: number, revenue: string, refunded: string) =>
        `${orders} طلب · ${revenue} إيراد · ${refunded} مسترد`,
      searchPlaceholder: "ابحث باسم الطالب أو الكتاب...",
      noOrders: "لا توجد طلبات مطابقة للفلاتر.",
      order: "الطلب",
      exportExcel: "تصدير Excel",
      refresh: "تحديث",
      lastSynced: (time: string) => `آخر تحديث ${time}`,
      loading: "جاري تحميل الطلبات...",
      loadError: "تعذر تحميل الطلبات الفعلية من الـ API المحلي.",
      coupon: "الكوبون",
      discount: "الخصم",
      netAmount: "صافي المبلغ",
    },
    lending: {
      title: "الإعارة",
      subtitle: (active: number, returned: number, overdue: number) =>
        `${active} نشطة · ${returned} تم إرجاعها · ${overdue} متأخرة`,
      activeLoans: "الإعارات النشطة",
      owner: "المالك",
      borrower: "المستعير",
      lent: "تاريخ الإعارة",
      due: "تاريخ الاستحقاق",
      returned: "تم الإرجاع",
      noRecords: "لا توجد سجلات إعارة مطابقة للفلاتر.",
    },
    settings: {
      title: "الإعدادات",
      subtitle: "إدارة الحساب وتفضيلات المنصة",
      account: "الحساب",
      platform: "المنصة",
      notifications: "الإشعارات",
      security: "الأمان",
      interface: "الواجهة",
      adminLanguage: "لغة لوحة الإدارة",
      adminLanguageDesc: "اختر اللغة واتجاه النص المستخدمين داخل لوحة التحكم.",
      english: "English",
      arabic: "العربية",
      enableLending: "تفعيل إعارة الكتب",
      enableLendingDesc: "السماح للطلاب بإعارة الكتب لطلاب آخرين",
      autoSuspend: "إيقاف المستعيرين المتأخرين تلقائيا",
      autoSuspendDesc: "إيقاف المستعيرين الذين يتجاوزون مدة الإعارة بأكثر من 7 أيام",
      studentArabic: "واجهة عربية للطلاب",
      studentArabicDesc: "تعيين العربية كلغة افتراضية في تطبيق الطلاب",
      emailNotifications: "إشعارات البريد الإلكتروني",
      emailNotificationsDesc: "استلام رسائل للطلبات الجديدة والأحداث المهمة",
      overdueAlerts: "تنبيهات الإعارات المتأخرة",
      overdueAlertsDesc: "إرسال تنبيه عند تأخر كتاب مستعار",
      twoFactor: "المصادقة الثنائية",
      twoFactorDesc: "إضافة طبقة حماية إضافية لحساب الإدارة",
    },
    security: {
      title: "الأمان والمراقبة",
      subtitle: "متابعة أحداث الأمان ونشاط الأجهزة وحماية المحتوى عبر المنصة.",
      totalEvents: "إجمالي الأحداث",
      deviceBlocked: "أجهزة محظورة",
      accessDenied: "رفض الوصول",
      screenshots: "محاولات لقطة شاشة",
      pendingResets: "طلبات تغيير قيد الانتظار",
      criticalEvents: "أحداث حرجة",
      resetRequests: "طلبات تغيير الجهاز",
      resetRequestsDesc: "طلاب يطلبون ربط جهاز فعلي جديد بحساباتهم",
      securityEvents: "أحداث الأمان",
      searchEvents: "ابحث في الأحداث...",
      searchRequests: "ابحث في الطلبات...",
      allSeverity: "كل المستويات",
      allTypes: "كل الأنواع",
      allStatuses: "كل الحالات",
      dateFrom: "من تاريخ",
      dateTo: "إلى تاريخ",
      event: "الحدث",
      severity: "الخطورة",
      device: "الجهاز",
      time: "الوقت",
      reason: "السبب",
      submitted: "تم الإرسال",
      resolved: "تم الحل",
      approve: "موافقة",
      reject: "رفض",
      approveHint: "الموافقة تسمح للطالب بتسجيل جهاز جديد عند تسجيل الدخول التالي.",
      reviewed: "تمت المراجعة",
      markReviewed: "تحديد كمراجع",
      loading: "جاري التحميل...",
      loadError: "تعذر تحميل بيانات الأمان الفعلية من الـ API المحلي.",
      noComparisonData: "لا توجد بيانات مقارنة حتى الآن",
      approveSuccess: "تم قبول طلب تغيير الجهاز.",
      rejectSuccess: "تم رفض طلب تغيير الجهاز.",
      reviewSuccess: "تم تحديد حدث الأمان كمراجع.",
      actionError: "فشل الإجراء",
      noResetRequests: "لا توجد طلبات تغيير جهاز.",
      noEvents: "لا توجد أحداث مطابقة للفلاتر الحالية.",
      mvpTitle: "وضع API فعلي",
      mvpLine1: "هذه الصفحة تقرأ الآن المقاييس والأحداث وطلبات تغيير الجهاز من الـ API المحلي.",
      mvpLine2: "الباك إند ما زال يستخدم ملف JSON تجريبي محلي إلى أن يتم تفعيل Drizzle/Postgres.",
      detailsStudent: "الطالب",
      detailsBook: "الكتاب",
      detailsDevice: "الجهاز",
      detailsMessage: "الرسالة",
      detailsMetadata: "بيانات إضافية",
      recommendedAction: "الإجراء المقترح",
      recommendedDefault: "راجع هذا الحدث واتخذ الإجراء المناسب.",
      eventTypes: {
        device_registered: "تسجيل جهاز",
        device_verified: "تحقق من الجهاز",
        device_blocked: "حظر جهاز",
        device_reset_requested: "طلب تغيير جهاز",
        device_reset_approved: "قبول تغيير الجهاز",
        device_reset_rejected: "رفض تغيير الجهاز",
        reader_opened: "فتح القارئ",
        reader_access_denied: "رفض الوصول",
        license_check_failed: "فشل الترخيص",
        screenshot_attempt: "محاولة لقطة شاشة",
        suspicious_activity: "نشاط مشبوه",
        phone_changed: "تغيير الهاتف",
        phone_verification_code_sent: "إرسال كود الهاتف",
        phone_verified: "توثيق الهاتف",
        phone_verification_failed: "فشل توثيق الهاتف",
        two_factor_enabled: "تفعيل 2FA",
        two_factor_disabled: "تعطيل 2FA",
        two_factor_challenge_sent: "إرسال تحدي 2FA",
        two_factor_success: "نجاح 2FA",
        two_factor_failed: "فشل 2FA",
      },
      severities: {
        low: "منخفض",
        medium: "متوسط",
        high: "عال",
        critical: "حرج",
      },
    },
  },
};

type AdminTranslation = typeof translations.en;

interface AdminLanguageContextValue {
  language: AdminLanguage;
  isRTL: boolean;
  dir: "ltr" | "rtl";
  t: AdminTranslation;
  setLanguage: (language: AdminLanguage) => void;
  formatNumber: (value: number) => string;
  formatCurrency: (value: number) => string;
  formatDate: (iso: string, options?: Intl.DateTimeFormatOptions) => string;
}

const AdminLanguageContext = createContext<AdminLanguageContextValue | null>(null);

function getInitialLanguage(): AdminLanguage {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === "ar" || stored === "en" ? stored : "en";
}

export function AdminLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AdminLanguage>(getInitialLanguage);
  const isRTL = language === "ar";
  const dir = isRTL ? "rtl" : "ltr";
  const locale = isRTL ? "ar-EG" : "en-US";

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [dir, language]);

  const value = useMemo<AdminLanguageContextValue>(
    () => ({
      language,
      isRTL,
      dir,
      t: translations[language],
      setLanguage: setLanguageState,
      formatNumber: (value: number) => new Intl.NumberFormat(locale).format(value),
      formatCurrency: (value: number) =>
        language === "ar"
          ? `${new Intl.NumberFormat(locale).format(value)} ج.م`
          : `EGP ${new Intl.NumberFormat(locale).format(value)}`,
      formatDate: (iso: string, options?: Intl.DateTimeFormatOptions) =>
        new Date(iso).toLocaleDateString(locale, options),
    }),
    [dir, isRTL, language, locale],
  );

  return (
    <AdminLanguageContext.Provider value={value}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const ctx = useContext(AdminLanguageContext);
  if (!ctx) throw new Error("useAdminLanguage must be used within AdminLanguageProvider");
  return ctx;
}
